POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impva3VtaWvDpG9saWthYW4iLCJpZCI6IjY5YTA0OWI4Yjk3OTJjYjlmMjJhOGUxOCIsImlhdCI6MTc3MjExNDkzMn0.VUhGVcb9ubH2BuFdWg-sy0ymPUCDZ0tAuNvfyf7BFU0

{
    "title": "kokeillaan tokeneita",
    "author": "toinen",
    "url": "http://homepage.com"
}
