POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5NDU0MzYyZDNlNDBiMjhmZWE1Y2ZjYiIsImlhdCI6MTc2NjE2OTY1OX0.MRK1qw3bBjGniIFG-X6ct4KFZQKWdNn2jyzqAbTZ6Qo

{
    "title": "Token based auth",
    "author": "Based",
    "url": "http://homepage.com",
    "likes": 67,
    "userId": "69454362d3e40b28fea5cfcb"
}
