POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRrc25pa2thIiwiaWQiOiI2OTQ1NDM4MGQzZTQwYjI4ZmVhNWNmY2QiLCJpYXQiOjE3NzI0NTkzNTN9.JfXanIcF-BFYwDrucD00B8Cotzk9T-L6353d7kwXcUQ

{
    "title": "adding blog",
    "author": "kolmas",
    "url": "http://homepage.com"
}
