POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5NDU0MzYyZDNlNDBiMjhmZWE1Y2ZjYiIsImlhdCI6MTc2ODIyMzY2MX0.uSfJqLrSL0Kr-UPN2cWaymOMx2NxPVvEErwKaON_ZLI

{
    "title": "käyttäjäksi sisäänkirjautunut user",
    "author": "asdds",
    "url": "http://homepage.com",
    "likes": 7,
    "userId": "69454380d3e40b28fea5cfcd"
}
